apiVersion: apps/v1
kind: Deployment
metadata:
  name: any-method-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: any-method-api
  template:
    metadata:
      labels:
        app: any-method-api
    spec:
      containers:
      - image: gcr.io/${PROJECT}/any-method-api:${TAG}
        name: any-method-api
        env:
          - name: SLEEP
            valueFrom:
              configMapKeyRef:
                name: api-params
                key: SLEEP
          - name: RAND500DIV
            valueFrom:
              configMapKeyRef:
                name: api-params
                key: RAND500DIV
          - name: DUMMY
            valueFrom:
              configMapKeyRef:
                name: api-params
                key: DUMMY
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    # cloud.google.com/backend-config: '{"default": "custom-health-check"}'

  labels:
    app: any-method-api
  name: any-method-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: any-method-api
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: any-method-api
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: any-method-api
            port:
              number: 80
          # serviceName: any-method-api
          # servicePort: 80apiVersion: v1
---
apiVersion: v1
data:
  SLEEP: ""
  RAND500DIV: "2"
  DUMMY: ""
kind: ConfigMap
metadata:
  name: api-params
  namespace: default
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: custom-health-check
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 80
    type: HTTP
    requestPath: /test